FROM ubuntu:20.04 as base

# Actualizar e instalar paquetes necesarios
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    wireshark \
    vsftpd \
    apache2 \
    openssh-server \
    iproute2 \
    make \
    gcc \
    php \
    php-cli \
    nano \
    vim \
    x11-utils \
    default-jdk \
    wget \
    sudo \
    && rm -rf /var/lib/apt/lists/*

# Descargar Tomcat 9.0.30
RUN wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.30/bin/apache-tomcat-9.0.30.tar.gz && \
    tar -xzf apache-tomcat-9.0.30.tar.gz && \
    mv apache-tomcat-9.0.30 /opt/tomcat && \
    rm apache-tomcat-9.0.30.tar.gz

# Exponer puertos: 80 para Apache, 22 para SSH, 20 y 21 para FTP, 8080 para Tomcat
EXPOSE 80 22 20 21 8080

# Copiar script de inicio personalizado
COPY start_services.sh /usr/local/bin/start_services.sh

# Establecer permisos y ejecutar el script al iniciar el contenedor
RUN chmod +x /usr/local/bin/start_services.sh
CMD ["start_services.sh"]
#RUN /usr/local/bin/start_services.sh
